name: cadet
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=21.1.7
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - blockbuster==1.5.26
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - fastapi==0.127.0
      - forbiddenfruit==0.1.4
      - frozenlist==1.8.0
      - googleapis-common-protos==1.72.0
      - groq==0.37.1
      - grpcio==1.76.0
      - grpcio-tools==1.75.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema-rs==0.29.1
      - langchain==1.1.3
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.2.0
      - langchain-groq==1.1.1
      - langchain-openai==1.1.3
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-api==0.6.15
      - langgraph-checkpoint==3.0.1
      - langgraph-cli==0.4.11
      - langgraph-prebuilt==1.0.5
      - langgraph-runtime-inmem==0.20.1
      - langgraph-sdk==0.3.0
      - langserve==0.3.3
      - langsmith==0.4.59
      - marshmallow==3.26.1
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.14.0
      - numpy==2.3.5
      - openai==2.11.0
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-http==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.5
      - ormsgpack==1.12.0
      - pandas==2.3.3
      - plotly==6.5.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psycopg2-binary==2.9.11
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyjwt==2.10.1
      - pytest==7.4.3
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - sqlparse==0.4.4
      - sse-starlette==2.1.3
      - starlette==0.50.0
      - structlog==25.5.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - truststore==0.10.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - uuid-utils==0.12.0
      - uvicorn==0.40.0
      - watchfiles==1.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
